name = "fast-search"
compatibility_date = "2024-04-02"

[vars]
UPSTASH_REDIS_REST_URL = https://rapid-giraffe-49560.upstash.io
UPSTASH_REDIS_REST_TOKEN = AcGYASQgZDlkODkzYjUtMjY3ZC00YjJkLWE0NDgtNzNjMGRhZGFkYjk0M2EyZmZhYmIzOWFjNDdjOGE0Y2E5NzI3YzdhMDQ2YWY=